### ISSUE TITLE
NPM UMD package

### ISSUE THREAD

**Issue by rubensolx** [ConnectyCube/connectycube-js-sdk-releases#2]
Hi,
Do you plan release the JS (browser) version as a npm package (or adapt the current one to use UMD)?

This is very important for the ones that make use of bundlers and want to control the version of the lib (as the react-native and nodejs devs do currently)

Cheers,

**Comment by DaveLombardo** [comment]
Hi @rubensolx 

You can do that already, a minified version of SDK is available in npm registry

<img width="294" alt="testcc" src="https://user-images.githubusercontent.com/39332586/48473317-7e335880-e7f8-11e8-9b53-788edc13bd78.png">

so you probably can require it in your app

Is it what you are looking for?

**Comment by rubensolx** [comment]
Hi Dave,
What I checked is that the NodeJS SDK is available on NPM. I can't use it together with Webpack because within it is using a lot of internal Node libs.
This same package can also be used for JavaScript? I mean, if I add as externals all the Node requires, It'll work on the browser?

Best,

**Comment by ccvlad** [comment]
Hi @rubensolx 
To build with the Webpack you can add `externals: ['nativescript-xmpp-client', 'node-xmpp-client', 'node-fetch', 'form-data']` to the Webpack's config.
But make sure you connect the connectycube SDK as `require('connectycube')`, it's important to that the entry point was from connectycube/src/cubeMain.js

**Comment by rubensolx** [comment]
Awesome :)
Can you provide the source-map together with the minified file?

**Comment by ccvlad** [comment]
You don't need the source-map for previous advise, because the minified sdk won't use in your build. So, you able to use your own source-maps.

The ConnectyCube SDK has the source-map with minified file, but for build with Gulp+Browserify tools and nodejs libs ([cdn.jsdelivr.net/npm/connectycube](https://www.jsdelivr.com/package/npm/connectycube?path=dist)).  

We have a Webpack build for the browser version, it will be released later after tests.

**Comment by rubensolx** [comment]
I mean, not on build but on development mode.
That's pretty much the need for it :)

**Comment by DaveLomber** [comment]
As source-map file is provided now, so closing it
