### ISSUE TITLE
react-native build error starting v3.6.0

### ISSUE THREAD

**Issue by chansc2016** [ConnectyCube/connectycube-js-sdk-releases#53]
starting from v3.6.0 above, all consist of build error 

step to reproduce:
1) react native init newProject
2) npm i react-native-connectycube
3) import ConnectyCube from "react-native-connectycube";  --- in App.js
4) react-native run-ios

<img width="577" alt="Screenshot 2020-11-16 at 3 54 49 PM" src="https://user-images.githubusercontent.com/22651091/99226137-377ffb00-2824-11eb-94c2-d8077d948728.png">

**Comment by ccvlad** [comment]
Hi, @chansc2016 
Thanks for the report. It fails because can't find ['react-native-webrtc'](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/iOSInstallation.md#ios-podfile) in Podfile for iOS.
We will release a new version with a fix of the issue and I will update you here.

**Comment by ccvlad** [comment]
@chansc2016 

You are able to install `react-native-connectycube` v3.7.6 and check ([release 3.7.6](https://github.com/ConnectyCube/connectycube-js-sdk-releases/releases/tag/3.7.6)).

FYI. You should to connect the `react-native-webrtc` library if you want to use video/audio calls ([guide](https://developers.connectycube.com/reactnative/videocalling?id=connect-webrtc-lib)).
